services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    healthcheck:
        test: ["CMD-SHELL", "mongosh --eval \"db.adminCommand('ping')\" --quiet"]
        interval: 10s
        timeout: 5s
        retries: 5
    networks:
      - InvoiceAINetwork

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - InvoiceAINetwork

  rabbitmq:
    image: rabbitmq:3.12.14-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - InvoiceAINetwork

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - InvoiceAINetwork

networks:
  InvoiceAINetwork:
    driver: bridge
